
os: osx
# sudo: required


# before_install:
#   - brew update

install:
  # - brew install boost
  - brew install llvm@3.7
  # - brew install netcdf
  - brew install cppcheck qt
  - brew link qt5 --force
  # - 
script:
  - qmake CONFIG+=debug -o Makefile build.pro
  - make -j4
  - cd bin/
  - ls
  - ./run_tests.sh